/**
 * Person Details Modal Script
 * Handles displaying detailed information about family members
 * Basic genealogical data is loaded from GEDCOM, this file contains additional details
 */

// Additional person data (photos, documents, contact info, bios)
// Names, dates, and relationships come from GEDCOM
// This constant is now deprecated - all data is loaded from GEDCOM
// Kept for backward compatibility in case GEDCOM data is unavailable
const personData = {
    'grandma-linda': {},
    'martin': {},
    'doris': {},
    'mom-sarah': {},
    'dad-robert': {},
    'uncle-tom': {},
    'uncle-tom-first-wife': {},
    'aunt-linda': {},
    'myself': {},
    'brother-mike': {},
    'cousin-jenny': {},
    'jason-porter': {},
    'mackenzie-porter': {}
};

// Get person info from GEDCOM
function getPersonInfo(personId) {
    const gedcomId = window.gedcomLoader ? window.gedcomLoader.getGedcomId(personId) : null;
    const parser = window.gedcomLoader ? window.gedcomLoader.getParser() : null;
    
    if (gedcomId && parser) {
        const individual = parser.getIndividual(gedcomId);
        if (individual) {
            const displayName = individual.name.given ? individual.name.given.split(' ')[0] : individual.name.full;
            return {
                name: displayName,
                fullName: individual.name.full,
                years: GedcomParser.formatYears(individual.birthDate, individual.deathDate)
            };
        }
    }
    
    // Fallback to empty values if GEDCOM not loaded
    return {
        name: '',
        fullName: '',
        years: ''
    };
}

// Initialize modal when DOM is ready
document.addEventListener('DOMContentLoaded', async function() {
    // Wait for GEDCOM to load
    if (window.gedcomLoader) {
        await window.gedcomLoader.initialize();
    }
    
    createModal();
    attachClickHandlers();
});

// Create the modal structure
function createModal() {
    const modal = document.createElement('div');
    modal.id = 'person-modal';
    modal.className = 'modal';
    modal.innerHTML = `
        <div class="modal-content">
            <span class="modal-close">&times;</span>
            <div class="modal-body">
                <h2 id="modal-person-name"></h2>
                <p id="modal-person-full-name" class="full-name"></p>
                <p id="modal-person-years" class="years"></p>
                <p id="modal-person-relation" class="relation"></p>
                
                <div id="modal-person-bio" class="bio-section"></div>
                
                <div class="modal-section" id="marriages-section">
                    <h3>Marriages</h3>
                    <div id="modal-marriages"></div>
                </div>
                
                <div class="modal-section" id="photos-section">
                    <h3>Photos</h3>
                    <div id="modal-photos" class="photos-grid"></div>
                </div>
                
                <div class="modal-section" id="documents-section">
                    <h3>Documents</h3>
                    <div id="modal-documents" class="documents-grid"></div>
                </div>
                
                <div class="modal-section" id="addresses-section">
                    <h3>Contact Information</h3>
                    <div id="modal-addresses"></div>
                </div>
            </div>
        </div>
    `;
    document.body.appendChild(modal);
    
    // Close modal when clicking X or outside
    const closeBtn = modal.querySelector('.modal-close');
    closeBtn.onclick = closeModal;
    
    modal.onclick = function(event) {
        if (event.target === modal) {
            closeModal();
        }
    };
    
    // Close on Escape key
    document.addEventListener('keydown', function(event) {
        if (event.key === 'Escape') {
            closeModal();
        }
    });
}

// Attach click handlers to all family member tiles
function attachClickHandlers() {
    const familyMembers = document.querySelectorAll('.family-member');
    familyMembers.forEach(member => {
        member.addEventListener('click', function() {
            const personId = this.id;
            showPersonDetails(personId);
        });
    });
}

// Show person details in modal
function showPersonDetails(personId) {
    const personDetails = personData[personId] || {};
    const personInfo = getPersonInfo(personId);
    
    const modal = document.getElementById('person-modal');
    
    // Set basic info from GEDCOM
    document.getElementById('modal-person-name').textContent = personInfo.name;
    document.getElementById('modal-person-full-name').textContent = personInfo.fullName;
    document.getElementById('modal-person-years').textContent = personInfo.years;
    
    // Get relation from family member element (generated by GEDCOM loader)
    const familyMemberElement = document.getElementById(personId);
    const relationText = familyMemberElement ? familyMemberElement.querySelector('.relation')?.textContent || '' : '';
    document.getElementById('modal-person-relation').textContent = relationText;
    
    // Get data from GEDCOM (or fallback to personData)
    const gedcomId = window.gedcomLoader ? window.gedcomLoader.getGedcomId(personId) : null;
    const parser = window.gedcomLoader ? window.gedcomLoader.getParser() : null;
    
    let bio = '';
    let photos = [];
    let documents = [];
    let addresses = { physical: [], virtual: [] };
    
    if (gedcomId && parser) {
        // Get data from GEDCOM
        bio = parser.getBio(gedcomId);
        photos = parser.getPhotos(gedcomId);
        documents = parser.getDocuments(gedcomId);
        addresses = parser.getAddresses(gedcomId);
    }
    
    // Fallback to personData if GEDCOM data is empty
    if (!bio && personDetails.bio) {
        bio = personDetails.bio;
    }
    if (photos.length === 0 && personDetails.photos) {
        photos = personDetails.photos;
    }
    if (documents.length === 0 && personDetails.documents) {
        documents = personDetails.documents;
    }
    if (addresses.physical.length === 0 && addresses.virtual.length === 0 && personDetails.addresses) {
        addresses = personDetails.addresses;
    }
    
    // Set bio
    const bioSection = document.getElementById('modal-person-bio');
    if (bio) {
        bioSection.innerHTML = `<p class="bio">${bio}</p>`;
        bioSection.style.display = 'block';
    } else {
        bioSection.style.display = 'none';
    }
    
    // Set marriages
    const marriagesContainer = document.getElementById('modal-marriages');
    const marriagesSection = document.getElementById('marriages-section');
    const marriagesAttr = familyMemberElement ? familyMemberElement.getAttribute('data-marriages') : null;
    
    if (marriagesAttr) {
        try {
            const marriages = JSON.parse(marriagesAttr);
            if (marriages && marriages.length > 0) {
                let marriagesHTML = '<div class="marriages-list">';
                marriages.forEach((marriage, index) => {
                    const spouseInfo = getPersonInfo(marriage.spouse);
                    const spouseName = spouseInfo.fullName || spouseInfo.name || marriage.spouse;
                    
                    let statusText = '';
                    let statusClass = '';
                    switch(marriage.status) {
                        case 'married':
                            statusText = 'Married';
                            statusClass = 'status-married';
                            break;
                        case 'divorced':
                            statusText = 'Divorced';
                            statusClass = 'status-divorced';
                            break;
                        case 'widowed':
                            statusText = 'Widowed';
                            statusClass = 'status-widowed';
                            break;
                        case 'deceased':
                            statusText = 'Deceased';
                            statusClass = 'status-deceased';
                            break;
                        default:
                            statusText = marriage.status;
                            statusClass = 'status-other';
                    }
                    
                    const dateRange = marriage.end ? `${marriage.start}-${marriage.end}` : `${marriage.start}-present`;
                    const marriageLabel = marriages.length > 1 ? `Marriage ${index + 1}` : 'Marriage';
                    
                    marriagesHTML += `
                        <div class="marriage-item">
                            <div class="marriage-header">
                                <strong>${marriageLabel}</strong>
                                <span class="marriage-status ${statusClass}">${statusText}</span>
                            </div>
                            <p><strong>Spouse:</strong> ${spouseName}</p>
                            <p><strong>Duration:</strong> ${dateRange}</p>
                        </div>
                    `;
                });
                marriagesHTML += '</div>';
                marriagesContainer.innerHTML = marriagesHTML;
                marriagesSection.style.display = 'block';
            } else {
                marriagesSection.style.display = 'none';
            }
        } catch (e) {
            console.error('Error parsing marriages data:', e);
            marriagesSection.style.display = 'none';
        }
    } else {
        marriagesSection.style.display = 'none';
    }
    
    // Set photos
    const photosContainer = document.getElementById('modal-photos');
    const photosSection = document.getElementById('photos-section');
    if (photos && photos.length > 0) {
        photosContainer.innerHTML = photos.map(photo => `
            <div class="photo-item">
                <img src="${photo.src}" alt="${photo.caption}">
                <p class="photo-caption">${photo.caption}</p>
            </div>
        `).join('');
        photosSection.style.display = 'block';
    } else {
        photosSection.style.display = 'none';
    }
    
    // Set documents
    const documentsContainer = document.getElementById('modal-documents');
    const documentsSection = document.getElementById('documents-section');
    if (documents && documents.length > 0) {
        documentsContainer.innerHTML = documents.map(doc => `
            <div class="document-item">
                <img src="${doc.src}" alt="${doc.caption}">
                <p class="document-caption">${doc.caption}</p>
            </div>
        `).join('');
        documentsSection.style.display = 'block';
    } else {
        documentsSection.style.display = 'none';
    }
    
    // Set addresses
    const addressesContainer = document.getElementById('modal-addresses');
    const addressesSection = document.getElementById('addresses-section');
    let addressesHTML = '';
    
    if (addresses && addresses.physical && addresses.physical.length > 0) {
        addressesHTML += '<div class="address-group"><h4>Physical Addresses</h4>';
        addresses.physical.forEach(addr => {
            addressesHTML += `<p><strong>${addr.type}:</strong> ${addr.address}</p>`;
        });
        addressesHTML += '</div>';
    }
    
    if (addresses && addresses.virtual && addresses.virtual.length > 0) {
        addressesHTML += '<div class="address-group"><h4>Virtual Contacts</h4>';
        addresses.virtual.forEach(contact => {
            addressesHTML += `<p><strong>${contact.type}:</strong> ${contact.value}</p>`;
        });
        addressesHTML += '</div>';
    }
    
    if (addressesHTML) {
        addressesContainer.innerHTML = addressesHTML;
        addressesSection.style.display = 'block';
    } else {
        addressesSection.style.display = 'none';
    }
    
    // Show modal
    modal.style.display = 'block';
    document.body.style.overflow = 'hidden'; // Prevent background scrolling
}

// Close modal
function closeModal() {
    const modal = document.getElementById('person-modal');
    modal.style.display = 'none';
    document.body.style.overflow = ''; // Restore scrolling
}
